"""Baseline-calibration gate (F-06 / task-09).

The KPI dashboard is useless — actually worse than useless — when its
R/Y/G threshold bands are computed on < 4 weeks of data for a 44-sub
channel. The bands would lock in noise as signal (Goodhart trap). So:

- `weeks_of_data()`: counts full ISO weeks with >= 5 non-preliminary
  channel_metric_snapshots rows.
- `is_activated()`: thresholds are active only when BOTH the YAML
  says `calibration.activated: true` AND we have >= 4 weeks of data.
- `auto_compute_thresholds()`: when week 4 lands, derive 25/50/75
  percentile bands per metric and write them to
  `config/kpi-thresholds.yaml.proposed` for manual review by Yaroslav.
"""

from __future__ import annotations

import sqlite3
from dataclasses import dataclass
from datetime import date, datetime, timezone
from pathlib import Path
from typing import Any


# Hand-rolled YAML parse/emit — the YAML files this module touches are
# strictly flat key→{k:v} and key→scalar. Importing `pyyaml` would pull
# a new runtime dep for three fields. Keep stdlib-only.


REQUIRED_WEEKS = 4
MIN_SNAPSHOTS_PER_WEEK = 5


@dataclass(frozen=True)
class ThresholdBand:
    green_above: float | None
    yellow_above: float | None
    red_below: float | None


@dataclass(frozen=True)
class CalibrationStatus:
    weeks_of_data: int
    required_weeks: int
    start_date: str | None
    activated_in_config: bool
    is_activated: bool  # config flag AND weeks_of_data >= required_weeks


def _load_yaml(path: Path) -> dict[str, Any]:
    """Minimal YAML loader for the flat shape used here.

    Supports: top-level keys, one-level-nested keys (`key:\n  subkey:
    value`), scalars (int/float/null/bool/string), `# comment` lines, and
    `null`/`true`/`false`/`YYYY-MM-DD` values. Does NOT handle lists,
    anchors, or multi-line strings — we don't use those.
    """
    if not path.exists():
        return {}
    out: dict[str, Any] = {}
    current_key: str | None = None
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.rstrip()
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        indent = len(line) - len(line.lstrip())
        stripped = line.strip()
        if ":" not in stripped:
            continue
        key, _, value = stripped.partition(":")
        key = key.strip()
        value = _strip_inline_comment(value.strip())
        if indent == 0:
            if value == "":
                out[key] = {}
                current_key = key
            else:
                out[key] = _coerce(value)
                current_key = None
        else:
            if current_key is None:
                # Indented line with no parent — skip.
                continue
            out[current_key][key] = _coerce(value)
    return out


def _strip_inline_comment(value: str) -> str:
    """Remove `# ...` trailing comment unless inside quotes."""
    if not value:
        return value
    in_quote = False
    quote_char = ""
    for i, ch in enumerate(value):
        if ch in ("'", '"'):
            if not in_quote:
                in_quote, quote_char = True, ch
            elif quote_char == ch:
                in_quote = False
        elif ch == "#" and not in_quote:
            return value[:i].strip()
    return value.strip()


def _coerce(value: str) -> Any:
    """Coerce a YAML-ish scalar into Python types."""
    if value == "" or value == "null" or value == "~":
        return None
    if value == "true":
        return True
    if value == "false":
        return False
    # Quoted strings — strip the quotes.
    if len(value) >= 2 and value[0] == value[-1] and value[0] in ('"', "'"):
        return value[1:-1]
    # Numeric.
    try:
        if "." in value:
            return float(value)
        return int(value)
    except ValueError:
        return value  # bare string


def _dump_yaml(data: dict[str, Any]) -> str:
    lines: list[str] = ["# Auto-generated by calibration.auto_compute_thresholds()"]
    for key, value in data.items():
        if isinstance(value, dict):
            lines.append(f"{key}:")
            for subkey, subval in value.items():
                lines.append(f"  {subkey}: {_dump_scalar(subval)}")
        else:
            lines.append(f"{key}: {_dump_scalar(value)}")
    lines.append("")
    return "\n".join(lines)


def _dump_scalar(value: Any) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, str):
        return f"\"{value}\""
    return str(value)


def weeks_of_data(conn: sqlite3.Connection) -> int:
    """Count full ISO weeks where at least `MIN_SNAPSHOTS_PER_WEEK`
    distinct calendar days of non-preliminary channel_metric_snapshots exist.

    Counts DISTINCT days (not raw rows): one ingestion run inserts
    multiple metrics per day, so COUNT(*) would falsely satisfy the
    snapshot threshold from a single day's data (Gemini-3.1-pro F-01
    R1 HIGH).

    Uses ISO 8601 week numbering: normalize observed_on to that week's
    Monday before formatting so days spanning Dec 31 / Jan 1 land in
    the same week (Gemini F-01 R1 MED — SQLite %W otherwise splits at
    the year boundary).
    """
    # ISO-week Monday: shift `observed_on` back by ((weekday + 6) % 7) days,
    # where SQLite's strftime('%w', date) returns 0=Sunday..6=Saturday. This
    # collapses every day into its same-week Monday and avoids the
    # %W-at-year-boundary split (Gemini-3.1-pro F-01 R1 MED).
    row = conn.execute(
        """
        WITH weekly AS (
            SELECT strftime(
                       '%Y-%m-%d',
                       observed_on,
                       '-' || ((CAST(strftime('%w', observed_on) AS INTEGER) + 6) % 7) || ' days'
                   ) AS iso_week_monday,
                   COUNT(DISTINCT substr(observed_on, 1, 10)) AS n_days
            FROM channel_metric_snapshots
            WHERE preliminary = 0
            GROUP BY iso_week_monday
            HAVING n_days >= ?
        )
        SELECT COUNT(*) AS n FROM weekly
        """,
        (MIN_SNAPSHOTS_PER_WEEK,),
    ).fetchone()
    return row["n"] if row else 0


def load_status(
    conn: sqlite3.Connection,
    *,
    config_path: Path,
) -> CalibrationStatus:
    config = _load_yaml(config_path)
    cal = config.get("calibration") or {}
    weeks = weeks_of_data(conn)
    required = int(cal.get("required_weeks", REQUIRED_WEEKS))
    activated_flag = bool(cal.get("activated", False))
    return CalibrationStatus(
        weeks_of_data=weeks,
        required_weeks=required,
        start_date=cal.get("start_date"),
        activated_in_config=activated_flag,
        is_activated=activated_flag and weeks >= required,
    )


def auto_compute_thresholds(
    conn: sqlite3.Connection,
    *,
    output_path: Path,
    metric_keys: tuple[str, ...] = (
        "impressions",
        "impressionsClickThroughRate",
        "averageViewDuration",
        "averageViewPercentage",
        "views",
    ),
    grain: str = "weekly",
    required_weeks: int | None = None,
    existing_config_path: Path | None = None,
) -> dict[str, ThresholdBand]:
    """Compute 25/50/75 percentile bands per metric on a single time grain.

    Returns a dict and also writes the proposed YAML to `output_path`
    (typically `config/kpi-thresholds.yaml.proposed`) for Yaroslav's
    manual review.

    Args:
        grain: Time grain to filter snapshots by (default "weekly").
            CRITICAL — without grain filter, daily/weekly/monthly values
            for the same metric pile into one array → percentile bands
            mathematically nonsensical (Gemini-3.1-pro F-01 R1 HIGH).
        required_weeks: Minimum weeks of data needed to compute bands.
            Defaults to module-level REQUIRED_WEEKS but can be overridden
            so callers stay consistent with `load_status()` reading the
            same value from YAML (Gemini F-01 R1 LOW — divergent SOT).
        existing_config_path: If provided and the file exists, preserve
            its `calibration.start_date` instead of overwriting with
            today's date (Gemini F-01 R1 MED — original install date
            was being permanently erased on every recompute).
    """
    req_weeks = required_weeks if required_weeks is not None else REQUIRED_WEEKS
    computed: dict[str, ThresholdBand] = {}
    for key in metric_keys:
        values = [
            r["value_num"]
            for r in conn.execute(
                """
                SELECT value_num FROM channel_metric_snapshots
                WHERE metric_key = ?
                  AND grain = ?
                  AND preliminary = 0
                  AND value_num IS NOT NULL
                """,
                (key, grain),
            )
        ]
        if len(values) < MIN_SNAPSHOTS_PER_WEEK * req_weeks:
            computed[key] = ThresholdBand(None, None, None)
            continue
        values.sort()
        p25 = _percentile(values, 25)
        p50 = _percentile(values, 50)
        p75 = _percentile(values, 75)
        computed[key] = ThresholdBand(
            green_above=p75,
            yellow_above=p50,
            red_below=p25,
        )

    # Preserve original start_date if existing config has one.
    start_date = datetime.now(timezone.utc).date().isoformat()
    if existing_config_path is not None and existing_config_path.is_file():
        existing_cal = (_load_yaml(existing_config_path).get("calibration") or {})
        existing_start = existing_cal.get("start_date")
        if existing_start:
            start_date = existing_start

    # Write proposed YAML.
    yaml_doc: dict[str, Any] = {}
    for key, band in computed.items():
        yaml_doc[key] = {
            "green_above": band.green_above,
            "yellow_above": band.yellow_above,
            "red_below": band.red_below,
        }
    yaml_doc["calibration"] = {
        "start_date": start_date,
        "required_weeks": req_weeks,
        "activated": False,  # Yaroslav flips this after review.
    }
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(_dump_yaml(yaml_doc), encoding="utf-8")
    return computed


def _percentile(sorted_values: list[float], pct: float) -> float:
    """Linear-interpolation percentile — matches numpy.percentile default."""
    if not sorted_values:
        return 0.0
    if len(sorted_values) == 1:
        return float(sorted_values[0])
    k = (len(sorted_values) - 1) * (pct / 100.0)
    lo = int(k)
    hi = min(lo + 1, len(sorted_values) - 1)
    frac = k - lo
    return sorted_values[lo] * (1 - frac) + sorted_values[hi] * frac
